services:
  app:
    image: abhishekcareslot/app:latest
    build:
      context: ./Back-End
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Kolkata
    restart: always

  frontend:
    image: abhishekcareslot/frontend:latest
    build:
      context: ./Front-End
    ports:
      - "2025:80"
    depends_on:
      - app
    environment:
      - TZ=Asia/Kolkata
    restart: always
