version: "3.9"

services:
  app:
    image: abhishekcareslot/app:latest
    container_name: careslot-app
    ports:
      - "3000:3000"
    env_file:
      - ./Back-End/.env
    environment:
      - TZ=Asia/Kolkata
    restart: always

  frontend:
    image: abhishekcareslot/frontend:latest
    container_name: careslot-frontend
    ports:
      - "2025:80"
    depends_on:
      - app
    environment:
      - TZ=Asia/Kolkata
    restart: always
