version: "3.9"

services:
  app:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Back-End:/app
      - /app/node_modules
    env_file:
      - ./Back-End/.env
    environment:
      - TZ=Asia/Kolkata
    command: npm run dev

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "2025:80"
    depends_on:
      - app
    environment:
      - TZ=Asia/Kolkata
